stages:
  - test

postman_test:
  stage: test
  image: postman/newman
  script: 
    - newman run API-PickleRick.postman_collection.json
  artifacts:
    paths:
      - newman/
    when: always