stages:
  - test

postman_test:
  stage: test
  image: 
    name: postman/newman
    entrypoint: [""]
  script: 
    - newman run API-PickleRick.postman_collection.json
  artifacts:
    paths:
      - newman/
    when: always