stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Construyendo el proyecto..."

# Instalar las dependencias de Node.js
install_dependencies:
  stage: install
  image: node:16  # Usamos una imagen de Node.js que incluye npm
  script:
    - npm install  # Instalar todas las dependencias definidas en package.json

# Ejecutar las pruebas de Cypress
cypress_test:
  stage: test
  image: cypress/included:12.0.0  # Usamos la imagen oficial de Cypress
  script:
    - npm test  # Ejecuta el script "test" que correrá las pruebas de Cypress
  artifacts:
    paths:
      - cypress/videos  # Guardar los videos de las pruebas
      - cypress/screenshots  # Guardar las capturas de pantalla
  only:
    - master  # Ejecutar solo en la rama "master"

test-postman:
  stage: test
  image: node:16 # Usamos una imagen con Node.js preinstalado
  script:
    - newman run ./API-PickleRick.postman_collection.json --reporters cli,junit --reporter-junit-export ./newman/results.xml
  artifacts:
    paths:
      - newman/results.xml # Guardar el reporte de resultados
  only:
    - master